stages:
  - lint
eslint: 
  stage: lint
  variables: 
    NODE_VERSION: 14.17.0
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NMV_DIR="$HOME/.nvm" && . "$NMV_DIR/nvm.sh" --no-use
    - eval "[ -f .nmvrc ] && nmv install"
    - npm install
    - npm run lint